config/routes.rb
HowTo::Application.routes.draw do
  root to: "topics#index"

  resources :topics do
    resources :steps
  end

  #authorization
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
end


#== Route Map
# Generated on 21 Jul 2013 15:22
#
#     topic_steps GET    /topics/:topic_id/steps(.:format)          steps#index
#                 POST   /topics/:topic_id/steps(.:format)          steps#create
#  new_topic_step GET    /topics/:topic_id/steps/new(.:format)      steps#new
# edit_topic_step GET    /topics/:topic_id/steps/:id/edit(.:format) steps#edit
#      topic_step GET    /topics/:topic_id/steps/:id(.:format)      steps#show
#                 PUT    /topics/:topic_id/steps/:id(.:format)      steps#update
#                 DELETE /topics/:topic_id/steps/:id(.:format)      steps#destroy
#          topics GET    /topics(.:format)                          topics#index
#                 POST   /topics(.:format)                          topics#create
#       new_topic GET    /topics/new(.:format)                      topics#new
#      edit_topic GET    /topics/:id/edit(.:format)                 topics#edit
#           topic GET    /topics/:id(.:format)                      topics#show
#                 PUT    /topics/:id(.:format)                      topics#update
#                 DELETE /topics/:id(.:format)                      topics#destroy

app/models/step.rb
# == Schema Information
#
# Table name: steps
#
#  id         :integer          not null, primary key
#  position   :integer
#  content    :text
#  topic_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Step < ActiveRecord::Base
  belongs_to :topic
  validates :position, :content, presence: true
  attr_accessible :content, :position

  default_scope order('position ASC')
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  topic      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Topic < ActiveRecord::Base
  has_many :steps, dependent: :delete_all
  validates :title, presence: true

  attr_accessible :title, :topic
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize_user
    redirect_to "/auth/linkedin" unless session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :authorize_user, except: [:index, :show]
  before_filter :find_topic
  before_filter :find_step, only: [:show, :edit, :update, :destroy]

  def new
    @step = @topic.steps.build
  end

  def create
    @step = @topic.steps.build(params[:step])
    if @step.save
      flash[:notice] = "Step has been created."
      redirect_to [@topic, @step]
    else
      flash[:alert] = "Step has not been created."
      render action: "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @step.update_attributes(params[:step])
      flash[:notice] = "Step has been updated."
      redirect_to [@topic, @step]
    else
      flash[:alert] = "Step has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @step.destroy
    flash[:notice] = "Step has been deleted."
    redirect_to @topic
  end

private
  def find_topic
    @topic = Topic.find(params[:topic_id])
  end

  def find_step
    @step = @topic.steps.find(params[:id])
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authorize_user, except: [:index, :show]
  before_filter :find_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  def index
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to @topic, notice: 'How To Topic was successfully created.'    
    else
      flash[:alert] = "How To Topic was not created."
      render action: "new"
    end
  end

  def show
  end

  # GET /topics/1/edit
  def edit
  end

  def update
    if @topic.update_attributes(params[:topic])
      redirect_to @topic, notice: 'How To Topic was successfully updated.'
    else
      flash[:alert] = "How To Topic has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @topic.destroy
    flash[:notice] = "How To Topic has been deleted."
    redirect_to topics_path
  end

  private
    def find_topic
      @topic = Topic.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The How To Topic you were looking for could not be found."
      redirect_to topics_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>How To...</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class = 'flash' id = '<%= key %>'>
     <%= value %>
  </div>

<% end %>

<% if current_user %>
  Signed in as <%= current_user.name %>!
  <%= link_to "Sign out", signout_path %>
<% else %>
  <%= link_to "Sign in with Linkedin", "/auth/linkedin" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@topic, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2>Step has not been created.</h2>
      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :position ,"Step Number" %> <br>
    <%= f.number_field :position %>
  </p>
  <p>
    <%= f.label :content ,"Description" %> <br>
    <%= f.text_area :content %>   
  </p>
  <%= f.submit %>
<% end %>

app/views/steps/edit.html.erb
<h1>Edit Step</h1>
<p id="notice"><%= notice %></p>

<%= render "form" %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render "form" %>

app/views/steps/show.html.erb
<div id = "step">
  <h2>Step: <%= @step.position %></h2>
  <%= simple_format(@step.content) %>
  <br>
  <%= link_to "All Steps", @topic %>
  <%= link_to "Edit Step", [:edit, @topic, @step] %>
  <%= link_to "Delete Step", [@topic, @step], method: :delete, confirm: "Are you sure you want to delete this ticket?" %>
</div>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2></h2>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "How to..." %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :topic, "Short Description (Optional)" %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<table>
  <tr>
    <th>How To...</th>
    <th>Description</th>
    <th></th>
 </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= link_to topic.title, topic %></td>
    <td><%= topic.topic %></td>
    <td><%= link_to 'Delete', topic, method: :delete, id: topic.id,  data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Description:</b>
  <%= @topic.topic %>
</p>

<ul id='steps'>
  <% @topic.steps.each do |step| %>
    <li>
      <%= link_to step.position, [@topic, step] %>: 
      <%= step.content %>
    </li>
  <% end %>
</ul>
<%= link_to 'New Step', new_topic_step_path(@topic) %> |
<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to "All How-To's", topics_path %>